[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fs_permissions = [{ access = "read-write", path = "./"}]

optimizer = true
optimizer_runs = 200
solc = "0.8.23"
evm_version="shanghai"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }