[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

optimizer = true
optimizer_runs = 200
solc = "0.8.23"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }